### ISSUE TITLE
Oplevering Moodle 4.2 + PHP 8.0

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-tool_groupautoenrol#1]
Graag informeren wij jullie over de oplevering van de Moodle plug-in(s) en eventuele aanpassingen die jullie hebben aangevraagd. Zouden jullie de functionaliteit ervan kunnen controleren en nagaan of alles naar verwachting werkt? Eventuele vragen of opmerkingen vernemen wij graag.

Bijgevoegd vinden jullie de links naar de repositories:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-tool_groupautoenrol/tree/86bwwnb0j-MOODLE42

Na jullie testen zien we graag jullie akkoord tegemoet voor het doorvoeren van de wijzigingen naar de main/master branch.

**Comment by gemguardian** [comment]
@luukverhoeven dit is akkoord. 

Graag de huidige Main versie een aparte branch geven. 

Kunnen jullie ook de release op Moodle.org regelen?

**Comment by luukverhoeven** [comment]
@gemguardian Doorgezet naar main, en gereleased op Moodle.org https://moodle.org/plugins/tool_groupautoenrol/versions
