### ISSUE TITLE
Increase size of groupslist col

### ISSUE THREAD

**Issue by pascal-my** [Lesterhuis-Training-en-Consultancy/moodle-tool_groupautoenrol#2]
Hello,

[camcgee](https://github.com/camcgee) made a pull request on my code : https://github.com/pascal-my/moodle-local_groupautoenrol/pull/1 : 

_Hi, we have a Moodle install with high enrollment courses and large numbers of groups for course discussions. This plugin has been extremely helpful but due to the number of groups, there's an error where some courses the list of groups is exceeding the column size. We've manually changed the size of the column in our database, but I'm proposing to increase this in the DB install as well._

Maybe, you should considerate change the size of the column in your DB install as well ?

:)

**Comment by gemguardian** [comment]
@pascal-my thank you. 

Yes we will @luukverhoeven can you cherry-pick this pull request?

**Comment by luukverhoeven** [comment]
Hi @gemguardian, I've noticed that these updates will only apply to new installations. There doesn't seem to be anything in `upgrade.php` that would convert this column for existing installations. How would you like us to proceed with this issue?

Additionally, I suggest considering the `text` data type for the column to ensure its length never exceeds the limit. Although the patch increases the limit, it might still not be sufficient for all cases.

**Comment by gemguardian** [comment]
@luukverhoeven if you can do this within 2 hours I am okay with the suggested changes. If that's not the case then we will leave it open for some other time.

**Comment by luukverhoeven** [comment]
@pascal-my, I appreciate the update on the merge and want to express my thanks for the pull request, @camcgee.

@gemguardian, I've implemented the changes within an hour. Please test the functionality on the branch https://github.com/Lesterhuis-Training-en-Consultancy/moodle-tool_groupautoenrol/tree/86by67h5c-increase-size-grouplist  to verify if it operates as expected.

**Comment by camcgee** [comment]
@luukverhoeven thanks very much for addressing this! I've tested this on our testing Moodle install:

- Uninstalled plugin
- Verified that table mdl_tool_groupautoenrol was removed in uninstall
- Installed plugin from branch 86by67h5c-increase-size-grouplist
- Verified that new table mdl_tool_groupautoenrol existed
- Added 250 groups to a Moodle course
- Turned on plugin for the course and selected "Enable automatic enrolment in groups for this course" and "Enrol users in selected groups only", selecting all 250 groups
- Added new enrollments
- Confirmed new enrollments were added to selected groups

**Comment by gemguardian** [comment]
@camcgee thank you for testing this. @luukverhoeven with this outcome it seems to operated as espected, please push to Main and release on Moodle.org

**Comment by luukverhoeven** [comment]
Merged to master branch. Published as `4.2.1` version on Moodle.org https://moodle.org/plugins/tool_groupautoenrol/versions
